/**
 * Cline adapter — `cline/cline` (VS Code extension).
 *
 * Reads `AGENTS.md` and `.clinerules/`. Commands map to Cline workflows. MCP
 * lives in VS Code globalStorage (not the project), which we cannot safely write
 * into — so it's emitted under `.harness/.generated/` with placement
 * instructions. Cline has no subagents (Plan/Act only) and no hook layer.
 */
import type { Adapter, FileOutput, ProjectionResult } from './types.js';
import type { HarnessSpec } from '../config/canonical.js';
import { rootAgentsOutput, nestedAgentsOutputs, markdownDefOutputs } from './shared.js';
import { toRooStyleMcp, projectScoped, jsonFile } from '../mcp/transpile.js';

function project(spec: HarnessSpec): ProjectionResult {
  const files: FileOutput[] = [];
  const warnings: string[] = [];

  const root = rootAgentsOutput(spec, 'cline');
  if (root) files.push(root);
  files.push(...nestedAgentsOutputs(spec));

  // Commands -> Cline workflows (.clinerules/workflows/<name>.md, invoked via /name).
  files.push(...markdownDefOutputs(spec.commands, '.clinerules/workflows', 'commands'));

  if (spec.skills.length) {
    warnings.push(`Cline has no first-class skills surface; ${spec.skills.length} skill(s) not projected.`);
  }
  if (spec.agents.length) {
    warnings.push(`Cline has Plan/Act modes but no subagents; ${spec.agents.length} subagent(s) not projected.`);
  }
  if (spec.enforce.length) {
    warnings.push(`Cline has no hook layer; ${spec.enforce.length} enforce rule(s) are advisory only here.`);
  }

  // .clineignore from Read deny patterns.
  const ignorePatterns = spec.permissions.deny
    .filter((r) => r.tool === 'Read' && r.pattern)
    .map((r) => r.pattern as string);
  if (ignorePatterns.length) {
    files.push({
      path: '.clineignore',
      contents: `# Generated by meta-harness-studio from .harness/permissions.toml\n${ignorePatterns.join('\n')}\n`,
      capability: 'ignore',
      scope: 'project',
    });
  }

  // MCP -> globalStorage (cannot write safely); emit a reference artifact for the
  // project-scoped servers. user/local-scoped servers already live in the user's
  // global store, so they need no project bridge — surface them as a note instead.
  const projectServers = projectScoped(spec.mcp);
  const nonProject = spec.mcp.filter((s) => s.scope !== 'project');
  if (nonProject.length) {
    warnings.push(
      `${nonProject.length} MCP server(s) are scope=user/local — already global to Cline; manage them directly in globalStorage: ${nonProject
        .map((s) => s.name)
        .join(', ')}.`,
    );
  }
  if (projectServers.length) {
    files.push({
      path: '.harness/.generated/cline/cline_mcp_settings.json',
      contents: jsonFile(toRooStyleMcp(projectServers)),
      capability: 'mcp',
      scope: 'user',
      note: 'Merge into VS Code globalStorage: <globalStorage>/saoudrizwan.claude-dev/settings/cline_mcp_settings.json',
    });
  }

  return { files, warnings };
}

export const cline: Adapter = {
  id: 'cline',
  title: 'Cline',
  homepage: 'https://cline.bot',
  capabilities: {
    instructions: 'native',
    commands: 'native',
    subagents: 'none',
    hooks: 'none',
    mcp: 'shim',
    permissions: 'shim',
    outputStyles: 'none',
    skills: 'none',
    ignore: 'native',
  },
  project,
};
