/**
 * Codex adapter (CLI + Desktop share `~/.codex`, so one adapter covers both).
 *
 * Codex reads `AGENTS.md` natively. Machine config (MCP, approval, sandbox) lives
 * in `config.toml`; we emit a project-scoped `.codex/config.toml`, which only
 * loads for *trusted* projects — surfaced as a note. Codex expresses permissions
 * as approval_policy + sandbox, not per-tool patterns, so tool-pattern rules are
 * reported as not transferable rather than silently dropped.
 */
import type { Adapter, FileOutput, ProjectionResult } from './types.js';
import type { HarnessSpec, PermissionSpec } from '../config/canonical.js';
import { rootAgentsOutput, nestedAgentsOutputs, skillOutputs } from './shared.js';
import { toCodexMcpToml, projectScoped } from '../mcp/transpile.js';

const APPROVAL: Record<PermissionSpec['defaultMode'], string> = {
  allow: 'never',
  ask: 'on-request',
  deny: 'untrusted',
};

function permsAreDefault(p: PermissionSpec): boolean {
  return (
    p.defaultMode === 'ask' &&
    p.sandbox.mode === 'workspace-write' &&
    p.sandbox.network === false &&
    p.allow.length === 0 &&
    p.deny.length === 0 &&
    p.ask.length === 0
  );
}

function project(spec: HarnessSpec): ProjectionResult {
  const files: FileOutput[] = [];
  const warnings: string[] = [];

  const root = rootAgentsOutput(spec, 'codex');
  if (root) files.push(root);
  files.push(...nestedAgentsOutputs(spec));

  files.push(...skillOutputs(spec, '.codex/skills'));

  if (spec.commands.length) {
    warnings.push(
      `Codex has no project-scoped command location (custom prompts are user-global and deprecated). ${spec.commands.length} command(s) not projected — prefer skills, or copy to ~/.codex/prompts/.`,
    );
  }
  if (spec.agents.length) {
    warnings.push(`Codex has no first-class subagent file; ${spec.agents.length} subagent(s) not projected.`);
  }
  if (spec.outputStyles.length) {
    warnings.push(`Codex has no output-styles concept; ${spec.outputStyles.length} style(s) not projected.`);
  }

  const projectServers = projectScoped(spec.mcp);
  const nonProject = spec.mcp.filter((s) => s.scope !== 'project');
  if (nonProject.length) {
    warnings.push(
      `${nonProject.length} MCP server(s) are scope=user/local — place them in ~/.codex/config.toml: ${nonProject
        .map((s) => s.name)
        .join(', ')}.`,
    );
  }

  const p = spec.permissions;
  const includePerms = !permsAreDefault(p);
  if (includePerms && (p.allow.length || p.deny.length || p.ask.length)) {
    const n = p.allow.length + p.deny.length + p.ask.length;
    warnings.push(
      `Codex expresses permissions as approval_policy + sandbox, not per-tool patterns; ${n} tool rule(s) mapped only to defaults.`,
    );
  }

  if (projectServers.length || includePerms) {
    const parts: string[] = [
      '# Generated by meta-harness-studio from .harness/.',
      '# Project-scoped Codex config — loads only for TRUSTED projects. In ~/.codex/config.toml add:',
      `#   [projects."${spec.root}"]`,
      '#   trust_level = "trusted"',
      '',
    ];
    if (includePerms) {
      parts.push(`approval_policy = "${APPROVAL[p.defaultMode]}"`);
      parts.push(`sandbox_mode = "${p.sandbox.mode}"`);
      parts.push('');
      parts.push('[sandbox_workspace_write]');
      parts.push(`network_access = ${p.sandbox.network}`);
      parts.push('');
    }
    if (projectServers.length) {
      parts.push(toCodexMcpToml(projectServers));
      parts.push('');
    }
    files.push({
      path: '.codex/config.toml',
      contents: parts.join('\n').replace(/\n{3,}/g, '\n\n'),
      capability: 'mcp',
      scope: 'project',
      note: 'Mark the project trusted in ~/.codex/config.toml for this to load.',
    });
  }

  return { files, warnings };
}

export const codex: Adapter = {
  id: 'codex',
  title: 'Codex (CLI + Desktop)',
  homepage: 'https://developers.openai.com/codex',
  capabilities: {
    instructions: 'native',
    commands: 'shim',
    subagents: 'shim',
    hooks: 'shim',
    mcp: 'native',
    permissions: 'native',
    modes: 'native',
    outputStyles: 'none',
    skills: 'native',
    ignore: 'shim',
  },
  project,
};
